---
title: 'Bonanza Creek Snowshoe Hares: Exploratory Report'
author: "Anastasia Kunz"
date: "11/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(effsize)
library(broom)
library(palmerpenguins)
library(ggbeeswarm)
library(kableExtra)
```

# Bonanza Creek Snowshoe Hares: Exploratory Report
 Anastasia Kunz

## 1. Overview
Just cursory overview of what is included DO THIS LAST BUT DONT FORGET!!!!


## 2. Data and Analysis
A 3 - 4 sentence section in which you briefly describe the data, including citation & credit as needed, and provide an overview of the main analysis, statistical methods and tools used.
....All analyses are in R version 4.0.2 using RStudio version 1.3.1073.



Possible map and figure?? maybe

## 3. Exploratory Findings
### A. Annual juvenile hare trap counts
### B. Visualize Juvenille Hare Weights
### C. Juvenile Weight Comparison (Male & Female)
### D. Relationship Between Juvenile Weight and Hind Foot Length
linear model here



## 4. Summary


## 5. Citations

Kielland, K., F.S. Chapin, R.W. Ruess, and Bonanza Creek LTER. 2017. Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present ver 22. Environmental Data Initiative. https://doi.org/10.6073/pasta/03dce4856d79b91557d8e6ce2cbcdc14











